# Generated by Django 2.2 on 2021-07-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='Pretty Smelly', max_length=50),
            preserve_default=False,
        ),
    ]
